version: 2

models:
  - name: dim_allergies
    description: >
      Unique information for each allergy from the stg_synthea__allergies.
      Information about reactions were separated into the int_synthea__allergies_unpivoted
      to be used as a fact table to have a individual information about each reaction.
    columns:
      - name: allergy_source_id
        tests:
          - not_null
          - unique

  - name: dim_patients
    description: >
      Unique information for each patient
    columns:
      - name: patient_source_id
        tests:
          - not_null
          - unique
  
  - name: dim_medications
    description: >
      Unique information for each medication
    columns:
      - name: medication_source_id
        tests:
          - not_null
          - unique

  - name: dim_procedures
    description: >
      Unique information for each procedure
    columns:
      - name: unique_id
        tests:
          - not_null
          - unique