version: 2

models:
  - name: dim_patients
    description: >
      Unique information for each patient
    columns:
      - name: patient_source_id
        tests:
          - not_null
          - unique
  
  - name: dim_medications
    description: >
      Unique information for each medication
    columns:
      - name: medication_source_id
        tests:
          - not_null
          - unique

  - name: dim_procedures
    description: >
      Unique information for each procedure.
      unique_id is a combination of 'code-description' due to multiple possible descriptions to the same procedure code
    columns:
      - name: procedure_unique_id
        tests:
          - not_null
          - unique

  - name: dim_immunizations
    description: >
      Unique information for each immunization
    columns:
      - name: immunization_source_id
        tests:
          - not_null
          - unique

  - name: dim_organizations
    description: >
      Unique information for each organization
    columns:
      - name: organization_source_id
        tests:
          - not_null
          - unique

  - name: dim_encounters
    description: >
      Unique information for each encounter
      encounter_unique_id is a combination of 'code-description' due to multiple possible descriptions to the same encounter code
    columns:
      - name: encounter_unique_id
        tests:
          - not_null
          - unique